config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :liked_tweets
  resources :tweets do
    resources :tweets
  end
  devise_for :users
  root to: 'tweets#index'

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/liked_tweet.rb
class LikedTweet < ApplicationRecord
  belongs_to :user
  belongs_to :tweet
end

app/models/tweet.rb
class Tweet < ApplicationRecord
  belongs_to :user
  has_many :liked_tweets, dependent: :destroy
  belongs_to :parent, class_name: 'Tweet',
                      optional: true
  has_many :responses, class_name: 'Tweet', foreign_key: 'parent_id', dependent: :destroy
  validates :body, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :tweets, dependent: :destroy
  has_many :liked_tweets, dependent: :destroy

  validates :username, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username])
    devise_parameter_sanitizer.permit(:account_update, keys: [:username])
  end
end

app/controllers/concerns/user_controller.rb
class UsersController < ApplicationController
    # GET /profile
    def show
      @user = current_user
    end
  end

app/controllers/liked_tweets_controller.rb
class LikedTweetsController < ApplicationController
  before_action :set_liked_tweet, only: %i[ show edit update destroy ]

  # GET /liked_tweets
  def index
    @liked_tweets = LikedTweet.all
  end

  # GET /liked_tweets/1
  def show
  end

  # GET /liked_tweets/new
  def new
    @liked_tweet = LikedTweet.new
  end

  # GET /liked_tweets/1/edit
  def edit
  end

  # POST /liked_tweets
  def create
    @liked_tweet = LikedTweet.new(liked_tweet_params)

    if @liked_tweet.save
      redirect_to @liked_tweet, notice: "Liked tweet was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /liked_tweets/1
  def update
    if @liked_tweet.update(liked_tweet_params)
      redirect_to @liked_tweet, notice: "Liked tweet was successfully updated."
    else
      render :edit, status: :unprocessable_entity
    end
  end

  # DELETE /liked_tweets/1
  def destroy
    @liked_tweet.destroy
    redirect_to liked_tweets_url, notice: "Liked tweet was successfully destroyed."
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_liked_tweet
      @liked_tweet = LikedTweet.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def liked_tweet_params
      params.require(:liked_tweet).permit(:user_id, :tweet_id, :liked)
    end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  before_action :set_tweet, only: %i[show edit update destroy]
  before_action :authenticate_user!, except: %i[index show]
  # GET /tweets
  def index
    @tweets = Tweet.all
  end

  # GET /tweets/1
  def show; end

  # GET /tweets/new
  def new
    @tweet = Tweet.new
    @parent_tweet = Tweet.find(params['tweet_id']) if params['tweet_id']
  end

  # GET /tweets/1/edit
  def edit; end

  # POST /tweets
  def create
    @tweet = Tweet.new(tweet_params)
    p '####################################'
    p params
    p tweet_params
    p '####################################'
    @tweet.parent_id = params['tweet_id'] if params['tweet_id']

    @tweet.user = current_user

    if @tweet.save
      redirect_to root_path, notice: 'Tweet was successfully created.'
    else
      render :new, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /tweets/1
  def update
    if @tweet.update(tweet_params)
      redirect_to @tweet, notice: 'Tweet was successfully updated.'
    else
      render :edit, status: :unprocessable_entity
    end
  end

  # DELETE /tweets/1
  def destroy
    @tweet = Tweet.find(params[:id])
    @tweet.destroy
    p '######################################'
    redirect_to tweets_path
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_tweet
    @tweet = Tweet.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def tweet_params
    params.require(:tweet).permit(:body)
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/liked_tweets_helper.rb
module LikedTweetsHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TweetableAppPractice</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>
  <header>
    <%=link_to "Welcome, #{current_user.username}" if user_signed_in? %>
    <%=link_to "Sign in", new_user_session_path unless user_signed_in? %>
    <%=link_to "Sign up", new_user_registration_path unless user_signed_in? %>
    <%=link_to "Home", "#" if user_signed_in? %>
    <%=link_to "Profile", "#" if user_signed_in? %>
    <%=link_to "Sign out", destroy_user_session_path, data: { turbo_method: :delete } if user_signed_in? %>
    
  </header>
  <body>
    <%=notice%>
    <%=alert%>
    <%= yield %>
  </body>
</html>

app/views/liked_tweets/_form.html.erb
<%= form_with(model: liked_tweet) do |form| %>
  <% if liked_tweet.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(liked_tweet.errors.count, "error") %> prohibited this liked_tweet from being saved:</h2>

      <ul>
        <% liked_tweet.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :user_id, style: "display: block" %>
    <%= form.text_field :user_id %>
  </div>

  <div>
    <%= form.label :tweet_id, style: "display: block" %>
    <%= form.text_field :tweet_id %>
  </div>

  <div>
    <%= form.label :liked, style: "display: block" %>
    <%= form.check_box :liked %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/liked_tweets/_liked_tweet.html.erb
<div id="<%= dom_id liked_tweet %>">
  <p>
    <strong>User:</strong>
    <%= liked_tweet.user_id %>
  </p>

  <p>
    <strong>Tweet:</strong>
    <%= liked_tweet.tweet_id %>
  </p>

  <p>
    <strong>Liked:</strong>
    <%= liked_tweet.liked %>
  </p>

</div>

app/views/liked_tweets/edit.html.erb
<h1>Editing liked tweet</h1>

<%= render "form", liked_tweet: @liked_tweet %>

<br>

<div>
  <%= link_to "Show this liked tweet", @liked_tweet %> |
  <%= link_to "Back to liked tweets", liked_tweets_path %>
</div>

app/views/liked_tweets/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Liked tweets</h1>

<div id="liked_tweets">
  <% @liked_tweets.each do |liked_tweet| %>
    <%= render liked_tweet %>
    <p>
      <%= link_to "Show this liked tweet", liked_tweet %>
    </p>
  <% end %>
</div>

<%= link_to "New liked tweet", new_liked_tweet_path %>

app/views/liked_tweets/new.html.erb
<h1>New liked tweet</h1>

<%= render "form", liked_tweet: @liked_tweet %>

<br>

<div>
  <%= link_to "Back to liked tweets", liked_tweets_path %>
</div>

app/views/liked_tweets/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @liked_tweet %>

<div>
  <%= link_to "Edit this liked tweet", edit_liked_tweet_path(@liked_tweet) %> |
  <%= link_to "Back to liked tweets", liked_tweets_path %>

  <%= button_to "Destroy this liked tweet", @liked_tweet, method: :delete %>
</div>

app/views/tweets/_form.html.erb
<%= form_with(model: tweet) do |form| %>
  <% if tweet.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(tweet.errors.count, "error") %> prohibited this tweet from being saved:</h2>

      <ul>
        <% tweet.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :body, style: "display: block" %>
    <%= form.text_area :body %>
  </div>

  <div>
    <%= form.label :tweets_count, style: "display: block" %>
    <%= form.number_field :tweets_count %>
  </div>

  <div>
    <%= form.label :likes_count, style: "display: block" %>
    <%= form.number_field :likes_count %>
  </div>

  <div>
    <%= form.label :user_id, style: "display: block" %>
    <%= form.text_field :user_id %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/tweets/_form2.html.erb
<%= form_with(model: [parent_tweet, tweet]) do |form| %>
  <% if tweet.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(tweet.errors.count, "error") %> prohibited this tweet from being saved:</h2>

      <ul>
        <% tweet.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :body, style: "display: block" %>
    <%= form.text_area :body %>
  </div>


  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/tweets/_tweet.html.erb
<div id="<%= dom_id tweet %>">
  <p>
    <strong>Body:</strong>
    <%= tweet.body %>
  </p>

  <p>
    <strong>Tweets count:</strong>
    <%= tweet.tweets_count %>
  </p>

  <p>
    <strong>Likes count:</strong>
    <%= tweet.likes_count %>
  </p>

  <p>
    <strong>User:</strong>
    <%= tweet.user_id %>
  </p>

</div>

app/views/tweets/edit.html.erb
<h1>Editing tweet</h1>

<%= render "form", tweet: @tweet %>

<br>

<div>
  <%= link_to "Show this tweet", @tweet %> |
  <%= link_to "Back to tweets", tweets_path %>
</div>

app/views/tweets/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Tweets</h1>

<div id="tweets">
  <% @tweets.each do |tweet| %>
    <%= render tweet %>
    <p>
      <%= link_to "Show this tweet", tweet %>
      <%= link_to "Response", new_tweet_tweet_path(tweet)  %>
    </p>
  <% end %>
</div>

<%= link_to "New tweet", new_tweet_path %>

app/views/tweets/new.html.erb
<h1>New tweet</h1>

<%if @parent_tweet%>
  <%= render "form2", parent_tweet: @parent_tweet, tweet: @tweet %>
<%else%>
<%= render "form", tweet: @tweet %>
<%end%>
<br>

<div>
  <%= link_to "Back to tweets", tweets_path %>
</div>

app/views/tweets/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @tweet %>

<div>
  <%= link_to "Back to tweets", tweets_path %>
  <% if user_signed_in? && current_user.id == @tweet.user_id %>
  <%= link_to "Edit this tweet", edit_tweet_path(@tweet) %> |
  

  <%= button_to "Destroy this tweet", tweet_path(@tweet), method: :delete, "data-turbo":"false" %>
  <% end %>
</div>